### PR TITLE
Add framework for testing multiple valcodes

### PR DESCRIPTION
**Pull request by paulhauner**
This commit adds the basics needed to easily test multiple validator signature verification contracts. This was done for the immediate goal of adding some tests for impure contracts for issue #50, and it therefore includes the testing of two impure contracts (one with an `sload` and another with an `sstore`).

The new `valcodes.txt` file is introduced which contains a `pprint`'ed dict of valcode bytecode. This file is read using `ast.literal_eval()` during tests. This isn't a common pattern, but JSON doesn't support Python `bytes` and `pickle` isn't human-readable (I wanted both).

The `valcodes.txt` file was generated by the new `valcode_generator.py` file, which takes Serpent source, compiles it, then over-writes the `valcodes.txt` file. The intention of my design is that it is modular enough so that once we migrate away from Serpent we should only need to change this file. Serpent was not added to `requirements.txt` as I sense a desire to remove it from the repo; happy to add it to `requirements.txt` if desired.

Ideally more impure contracts should be tested (e.g., those which read gas information), however this is my first pull request here and I didn't want to go too far without some feedback.

Thanks! :smile:

### CODE REVIEW

**Comment by paulhauner** [comment]
I'm not sure why that last build failed. Here's the traceback from TravisCI:

```
$ pytest tests
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/config.py", line 329, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/travis/build/ethereum/casper/tests')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/config.py", line 360, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/travis/build/ethereum/casper/tests/conftest.py')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/build/ethereum/casper/tests/conftest.py", line 6, in <module>
    from ethereum.abi import ContractTranslator
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ethereum/__init__.py", line 11, in <module>
    from . import slogging  # noqa
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ethereum/slogging.py", line 6, in <module>
    from ethereum.utils import bcolors, is_numeric
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/ethereum/utils.py", line 13, in <module>
    from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
ERROR: could not load /home/travis/build/ethereum/casper/tests/conftest.py
```

To me, this error doesn't seem related to the commit.

AFAIK, I can't trigger a rebuild because I don't have write access to this repo. If someone gets a chance, I 'd be interested to see if the problem persists after a rebuild :)

**Comment by djrtwo** [comment]
just closed/reopened to trigger the build

**Comment by paulhauner** [comment]
Thanks

**Comment by ChihChengLiang** [comment]
looks like the issue is that recent rlp removed the decode and encode hex utils https://github.com/ethereum/pyrlp/commit/9f43bf5bc756ec97512e278f03d0599169cbcf6b#diff-abde48281f0cb82afb7f697a7c3f73d4

**Comment by paulhauner** [comment]
Yep, fails on my local machine with `rlp==1.0.0`. It seems that change affects all `1.0.0-beta...` releases.

However, It works on my local machine with `rlp==0.6.0`.

**Comment by paulhauner** [comment]
That'll do it! :grinning:

File: tests/test_valcode_purity.py [hunk 1]
```diff
@@ -0,0 +1,40 @@
+from ethereum import utils
+from ethereum.tools.tester import TransactionFailed
+import pytest
+
+def test_deposit_succeeds_with_pure_sig_validator(casper, funded_privkey,
```
Comment (djrtwo) [inline tests/test_valcode_purity.py]: Would probably be better to implement this more generically with `pytest.mark.parametrize`. See `test_voting` for an example https://github.com/ethereum/casper/blob/master/tests/test_voting.py#L7

**Comment by djrtwo** [comment]
This seems like a reasonable approach if we want to not include `serpent` in the requirements.

If we are willing to include `serpent` in `requirements.txt`, we could just have all of this as a more dynamic helper as a test utility, correct? Something like `get_valcode_with("sload")`?

I'm not really opposed to including `serpent` in the build for the time being. Thoughts @ChihChengLiang?

**Comment by paulhauner** [comment]
Yep, good call on parameterize! New commit uses it, and `assert_tx_failed`.

I agree about using `serpent`, it would be tidier to avoid using that `txt` file. Happy to implement dynamically :smile:

**Comment by ChihChengLiang** [comment]
I'm ok with or without serpent. but it's also not hard to write in vyper lll
```python
from vyper import compiler, optimizer, compile_lll
from vyper.parser.parser_utils import LLLnode
from ethereum.utils import bytes_to_int, privtoaddr

def mk_code(address):
    validation_code_maker_lll = LLLnode.from_list(['seq',
                                ['return', [0],
                                    ['lll',
                                        ['seq',
                                            ['calldatacopy', 0, 0, 128],
                                            ['call', 3000, 1, 0, 0, 128, 0, 32],
                                            ['eq', ['mload', 0], bytes_to_int(address)],
                                            ['return', 0, 32]
                                        ],
                                    [0]]
                                ]
                            ])
    validation_code_maker_lll = optimizer.optimize(validation_code_maker_lll)
    return compile_lll.assembly_to_evm(compile_lll.compile_to_assembly(validation_code_maker_lll))
mk_code(privtoaddr(1337))
```

File: tests/conftest.py [hunk 2]
```diff
@@ -262,25 +262,77 @@ def new_epoch():
...
+        )
+    return wrap_lll_list
+
+
+@pytest.fixture
+def mk_validation_code(wrap_lll_list):
+    def mk_validation_code(address, valcode_type):
+        valcodes_lll_lists = dict(
+            pure=wrap_lll_list(
+                ['seq',
```
Comment (ChihChengLiang) [inline tests/conftest.py]: Here is some repetition, but the readability is no worse than abstracting out.

Comment (paulhauner) [reply tests/conftest.py]: I also considered a "template" style for the LLL, where you specify an impure operation to be inserted at the top of the pure code (i.e., no repetition of actual signing code). I decided against because I thought it might be inflexible... Keen to hear your thoughts though!

Comment (djrtwo) [reply tests/conftest.py]: I think we should make a `tests/utils` folder and move the `valcodes_lll_lists` to a file in there that we import into conftest.py. Either just import the dict or make a function that takes the type of valcode as an argument ("pure", "sload", etc).

The `wrap_lll_list` also doesn't need to be a fixture at this point and should just be a helper function that lives in the utils file.

**Comment by paulhauner** [comment]
Alright, I got a little carried away and implemented tests for 27 different opcodes. I wanted to just halt it here and get your opinions on the following things:

1. The `build_pass_fail_matrix()` function in `test_valcode_purity.py`. It generates all the tests depending on valcode type (if it is prefixed with "pure_" it should pass, "impure_" it should fail). It's cool cause it's automatic, but it's a bit of a beast. Please give thoughts and alternatives.
2. In order to use "unused" opcodes, I had to drop them into the EVM code myself (I couldn't get Vyper LLL to compile them). This means that some valcodes are evm bytecode, others are LLL code. I was tempted to turn them all into bytecode, but I thought I'd get your opinions first.

Thanks! :smile:

**Comment by djrtwo** [comment]
First of all, this is super badass.

As for it being a beast, I think you have captured the complexity about as nicely as we are going to be able to at the moment. I'm unsure about integrating unused opcodes into vyper lll so the bytecode might be the way to go for now. As for the range that was chosen, vitalik mentioned in the past they those are designated for impure bytecodes in the future. I'm trying to see if I can find this fact documented anywhere so we can include it in a comment for posterity.

The only comment I have right now before I do a final review when you say so is a bit nit-picky. I previously suggested using a `get_` prefix in one my comments. I wasn't thinking. We're generally leaning away from using `get_` all over the place and have the function names be more explicit. Just chopping of `get_` from the names should do it.

**Comment by paulhauner** [comment]
Haha thanks!

Yep, I'm down to remove the `get_` prefix!

I want to do a couple more checks in the tests to cover for cases where a contract `throw` on deploy can be interpreted as a revert caused by the purity filter. 

I'll push them up and let you know when I'm ready.

**Comment by djrtwo** [comment]
Cool.

just fyi, we use the convention of prefixing the title of the PR with "[WIP]" to signal not ready for merge

**Comment by paulhauner** [comment]
Alright, ready for final review!

Next time I get some time I'll work to test that external-call-gas-setting scenario in the [purity checker](https://github.com/ethereum/research/blob/master/impurity/check_for_impurity.se). ETA early next week sometime.

Thanks!

**Comment by paulhauner** [comment]
Good call. Has been renamed :smile:
